### PR TITLE
Use default kernel name for default (current) env

### PR DESCRIPTION
**Pull request by minrk**
avoids missing key problems when moving between conda and non-conda managers

reverts unconditional removal of existing kernel specs, so that only those overridden will be replaced, rather than removing kernels that are properly installed.

Alternately:

- use default name for root env
- don't remove or replace installed kernels at all

Perhaps the best option is to just stop removing installed kernels, so that conda envs are strictly in addition to, rather than instead of, normally installed kernels.

### CODE REVIEW

**Comment by damianavila** [comment]
I like the general idea about the Python [default] poiting to the current environment... but that breaks when someone create a `default` environment... because, if I guess correctly, we will have two indistinguishable `Python[default]` poiting to different environments...

>Perhaps the best option is to just stop removing installed kernels, so that conda envs are strictly in addition to, rather than instead of, normally installed kernels.

I was thinking specifically on that option + removing the `Python[current_env]` from the kernelspecs set we are creating on the fly, otherwise people will have two options (`Python X` and `Python [current_env]` poiting to the very same environment (this is why the existing kernelspec were removed at first time... and because the lack of consitency between `Python X` and `Python [something]`).

Pinging @bollwyvl who is probably interested on this discussion as well...

**Comment by janschulz** [comment]
In the environment kernel manager, we currently use a prefix (`conda_<name>` and `conda_r_<name>`)  as the name of the kernel (+ display names similarly constructed).

**Comment by bollwyvl** [comment]
Thanks for this, folks!

Spitballing another approach:
- perhaps just accept that this needs more and custom UI, not based on the name/displayname nightmare that we've created
- don't try to do anything unexpected in the existing keys (`kernelspecs` and `defaults`)
- overload the handler to provide a list of kernel/env pairs

```yaml
{
  "kernelspecs": {...},
  "default": "python3",
  "kernelenvspecs: [
    # a full kernelspec
  ],
  "default_kernelenvspec": {
    "name": "python3",
    "env": "some-env",
    "type": "conda"
  }
}
```
- Then, monkeypatch the js for adding a notebook/changing kernels to take into account an env, but always lead with the canonical kernelspec name

**Comment by bollwyvl** [comment]
Another issue: currently, there is no way to extend nbconvert to use a custom KernelSpecManager... what would it be like to get a `kernel_manager_class` added there as well, instead of just using `open_new_kernel` (or whatever) directly?

**Comment by minrk** [comment]
@janschulz that's a good idea, I think adding a conda prefix/suffix to all conda-provided kernels is the right thing to do. I've updated this PR to do that.

Now the kernel-name keys are not the same as the display names, as these should generally be different, with name being a simple url-safe key, display_name being human-readable text. It now looks like this:

screen shot 2016-07-25 at 14 26 09

Default (current env) gets:

    Python [default]

and uses Jupyter's own default key, matching Jupyter's default behavior.
Root gets:

    Python [conda root]

and envs get:

    Python [conda env:name]

resolving ambiguity with envs named 'default' or 'root'.

**Comment by bollwyvl** [comment]
@minrk sounds good. I'll look into the test fails!

**Comment by damianavila** [comment]
Interesting idea... still breaks if you are dealing with a multi-user setup in conda, ie, having two `default` envs, one centralized and other per-user, but improves things a lot for the simple case. I probably have to do something similar to resolve the ambiguity of envs from the central or per user location, but this is maybe too specific to be inside this code base. 
So, in summary, +1 to this one.

**Comment by bollwyvl** [comment]
Created this PR-on-PR:
https://github.com/minrk/nb_conda_kernels/pull/1

**Comment by minrk** [comment]
Thanks, @bollwyvl!

**Comment by bollwyvl** [comment]
@minrk I think I've gotten the CI sorted... didn't mean to raise the other PR directly, but it does now include all the commits. Review from anyone else (@damianavila) welcome, but otherwise I am inclined to merge this and start the release cycle... actual distribution might have to wait, as this will necessitate builds of `nb_anacondacloud` and `nb_conda`, which rely on how those strings are structured on the javascript side... another argument for actually putting some JS into this thing in the future...

**Comment by damianavila** [comment]
@minrk @bollwyvl I will take a look today.

**Comment by bollwyvl** [comment]
Yar, i merged the one over on #40. Doing a few more cleanup things, new PR coming...

**Comment by damianavila** [comment]
OK, since this one was superseded by #40, I am going to close this one.
@minrk thanks for your work and discussion here.

**Comment by bollwyvl** [comment]
That PR being: 
https://github.com/Anaconda-Platform/nb_conda_kernels/pull/41

**Pull request closed without merging**
