### PR TITLE
[DO NOT MERGE] Run tests against latest Conda (4.5)

### PR DESCRIPTION
**Pull request by tjd2002**
There haven't been any commits here since April 2017, so the last time tests were run was against conda 4.3.16. Conda 4.4 seems to have broken things (see #73, #79), so this PR is here just to capture that in testing.

### CODE REVIEW

**Comment by tjd2002** [comment]
Hmm... the tests still pass because Travis seems to be using a cached copy of the installer at https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh

When I download that URL on my machine I get 4.5.1 (which I would expect to fail), but Travis-CI reports a conda version of 4.3.16 during testing. I'll open an issue to request an update of testing.

**Comment by tjd2002** [comment]
OK! With that change to .travis.yml, this PR is now testing against conda 4.5.4 (according to conda info during the Travis run), and the tests are still passing. (Including npm tests that apparently look for conda GUI elements in rendered notebooks).

This means that the testing environment is not capturing the breakage reported at #73,  or jupyterlab/jupyterlab/issues/4598. I'm somewhat stumped; @benbovy any insight?

**Comment by benbovy** [comment]
I think this is because of this: https://github.com/Anaconda-Platform/nb_conda_kernels/blob/f7b468090fc2f7fbf1dd56fe875f3e5c28051aa9/.travis.yml#L31

The conda executable is still found. I guess tests will not pass if for example you replace this line by

```
. $HOME/miniconda/etc/profile.d/conda.sh
```

You probably have to also replace `source activate nb_conda_kernels` by `conda activate nb_conda_kernels`.

In #73 I probably should update travis config and add a regression test...

**Comment by tjd2002** [comment]
That's certainly it, I'll try it out in this PR (unfortunately that's the only way I know of to run tests).

**Comment by tjd2002** [comment]
Hooray, the tests failed 😄!  (For the right reason--notebook couldn't start) 

From Travis log line 1641 https://travis-ci.org/Anaconda-Platform/nb_conda_kernels/jobs/383914096:
```
Timeout for http://localhost:8888/a@b/
Is the notebook server running?
```

**Comment by tjd2002** [comment]
PS: I think I found another reference to the conda executable, in nb_conda/handlers.py:211 
`cmdline = 'conda search --json'.split()`
If you can take a look at that one too that'd be great, if not I'll file an issue over there somewhere.

**Comment by mcg1969** [comment]
Yes, because conda 4.5 no longer puts `conda` in the PATH, `nb_conda_kernels` has to jump through some hoops in order to determine how to call `conda info --json`. I'm addressing these issues in #80 (among other things). Note that you have to be extra careful to get this right if `nb_conda_kernels` is installed in an environment other than `base`.

But note that I am not an official contributor to the package (though I know the people who are ;-)) so I can't say for sure that my work will get in there. We might want to break that out separately.

**Comment by mcg1969** [comment]
If you're working on this, I would recommend building a basic conda recipe into the repository itself. At the very least, this repo needs to own and control the post-link and pre-unlink scripts that are now found [here](https://github.com/conda-forge/nb_conda_kernels-feedstock/tree/master/recipe) instead.

**Comment by tjd2002** [comment]
[Apologies for the PR spam just now.] It seems like these issues cut across all the conda notebook extensions--It would be good to open an issue to discuss how all of them should deal with the transition to 4.4+ (including testing and backwards-compatibility). Perhaps the best place to do that is at the Anaconda-Platform/anaconda-nb-extensions meta-package repo?

**Comment by tjd2002** [comment]
Further discussion at Anaconda-Platform/anaconda-nb-extensions#168

**Pull request closed without merging**
