### PR TITLE
Fix #160

### LINKED ISSUE #160: Kernel spec metadata discards existing fields
Hey folks,

This issue was originally posted in https://github.com/fcollonval/jupyter_conda.

However it looks like it applies to this package more than `jupyter_conda`.

## Description

It looks like the original kernel spec metadata for a kernel is not kept when using the "conda version" of the kernel.

Glancing at the code briefly, it looks like the reason for this might be:

https://github.com/Anaconda-Platform/nb_conda_kernels/blob/1b9e821e7cafe388b633ba4fdb8feb3eec815d6c/nb_conda_kernels/manager.py#L196-L199

## Reproduce

1. Go to mybinder.org: https://mybinder.org/v2/gh/fcollonval/jupyter_conda/master?urlpath=lab
2. Install `xeus-python` from the conda packages manager
3. Do a `GET /api/kernelspecs` to retrieve the kernel specs (for example in the browser by entering: https://path/to/the/mybinder.org/api/kernelspecs)

Starting from version `0.8.0`, `xeus-python` includes the `debugger` key in the kernel specs metadata.

However this key is not present in the metadata for `xpython [conda env:notebook] *`:

image

## Expected behavior

The `metadata` for `xpython [conda env:notebook] *` should include `debugger: true` along `conda_env_name` and `conda_env_path`.

## Context

Binder link on Firefox 77.

## Related issues

- https://github.com/fcollonval/jupyter_conda/issues/45
- https://github.com/jupyterlab/debugger/issues/475

Thanks!

### PR DESCRIPTION
**Pull request by fcollonval**
Extend kernel metadata rather than overriding it.

### CODE REVIEW

**Comment by fcollonval** [comment]
@mcg1969 The current CI error is linked to the Python 2.7 test environment. The question is should testing against Python 2.7 be discontinued?

**Comment by mcg1969** [comment]
I'm open to changing the tests but I do think we should strive to support Python 2 as a target kernel. This seems like a package that would be useful to support people with legacy models and applications. Do you by any chance have an understanding as to why the post-install script is failing?

**Comment by fcollonval** [comment]
Michael, I saw that on conda-forge, a release 4.10.0_1 exists that removes the post link script. Will it be acceptable to add conda-forge as channel to generate the test environment?

**Comment by mcg1969** [comment]
Yes! A good solution

**Comment by mcg1969** [comment]
Or we can just install `conda-forge::ipykernel`

**Comment by mcg1969** [comment]
Thank you so much for this hard work.

**Comment by fcollonval** [comment]
You're welcome. I got a hard time with the Python 2.7 cases. But it seems it is now working. Let's hope the OSX will pass too.

**Pull request merged**
