### PR TITLE
update versioneer and github actions

### PR DESCRIPTION
**Pull request by mcg1969**

### CODE REVIEW

**Comment by mcg1969** [comment]
@basnijholt can you review this? This incorporates a version update and fixes to the tests.

**Comment by basnijholt** [comment]
Looks good!

Would you be open to a PR that adds pre-commit with autostyled code and linters that automatically upgrade to "modern" syntax where possible?

**Comment by mcg1969** [comment]
Note to team: merging without an explicit review, in coordination with @basnijholt

**Comment by mcg1969** [comment]
@basnijholt I'm more than happy to accept such PRs. Now that the testing is modernized we can cycle more quickly. Thank you!

**Pull request merged**
