### PR TITLE
Customize display name

### PR DESCRIPTION
**Pull request by fcollonval**
Allow user to customize display name through configuration:

```json
  "CondaKernelSpecManager": {
    "name_format": "{0}-{1}"
  }
```
The argument *0* is the language and the *1* is the environment name.

### CODE REVIEW

**Comment by fcollonval** [comment]
@mcg1969 
The reason the tests are not passing is the display name for the *root* environment. Indeed it does not follow the standard name format. Therefore if the user is able to specify that format, there is two possibilities to fix this:
- Forcing a special name for the *root* environment ignoring user configuration
- Use the same format for *root* and apply the user configuration is present

Failure encountered:
```
#    text: "Python [conda root]"
#    actualContent: "Python [conda env:root]"
```

**Comment by mcg1969** [comment]
Can we simply preserve the existing behavior if a formatting value has not been provided? I know it would be a bit clunky but you'd have to modify the Javascript tests too if you wanted to make this pass otherwise.

**Comment by fcollonval** [comment]
I went for the second option as the default name format is specified in the traitlet and not define in case the name_format is None (what is actually forbidden).

It is ready for merging if you agree on this.

**Comment by mcg1969** [comment]
OK, I'm merging! Thanks.

**Pull request merged**
