### PR TITLE
Upgrade `versioneer` to become Python 3.12 compatible

### PR DESCRIPTION
**Pull request by basnijholt**

### CODE REVIEW

**Comment by basnijholt** [comment]
@mcg1969 could you please take a look here and merge?

My base environment has Python 3.12 now (and likely other folks have that too). Since `nb_conda_kernels` is installed in the base env, there is an issue.

**Review by effigies — APPROVED** [review]
LGTM as a versioneer maintainer (no longer active, but little has changed).

**Review by mcg1969 — APPROVED** [review]
Sorry for the delay, all good!

**Comment by basnijholt** [comment]
The CI seems stuck somehow...

**Comment by mcg1969** [comment]
OK, I'll have to take a look but I can't this evening

**Comment by mcg1969** [comment]
Basically we need to change the testing matrix to a more modern set of operating systems

**Comment by mcg1969** [comment]
I'm working on a separate pull request to do this and simultaneously refresh the github actions. stay tuned

**Comment by mcg1969** [comment]
I'm going to drop Python 2 from the test matrix. Obviously that was long overdue. If anyone is still using Python 2.7 in their root environment, obviously with an old version of conda, they still have older versions of `nb_conda_kernels` available that will likely work just fine.

**Comment by mcg1969** [comment]
Closing in favor of #237

**Pull request closed without merging**
