### PR TITLE
Set up CI with Azure Pipelines

### PR DESCRIPTION
**Pull request by mcg1969**

### CODE REVIEW

**Comment by kaylangan** [comment]
I'm a Program Manager on Azure Pipelines. Let me know if you have any questions or suggestions. I'm happy to help!

**Comment by mcg1969** [comment]
Thanks for chiming in, @kaylangan! This effort is currently stalled pending resolution of issues being discussed here: https://github.com/Microsoft/vsts-tasks/issues/8299

**Comment by kaylangan** [comment]
@mcg1969 Thanks for your help and patience. The fix should be [all rolled out now](https://github.com/Microsoft/azure-pipelines-tasks/issues/8299#issuecomment-427095427). Let me know if you have any other issues.

**Comment by mcg1969** [comment]
Procrastination pays. GitHub actions (which I assume are an evolution of Azure pipelines) look promising.

**Pull request closed without merging**
