### PR TITLE
Fix conda executable not found (conda 4.4+)

### LINKED ISSUE #73: conda 4.4.7 does not work with nb_conda_kernels in new/reinstalled envs
In base env my launch log for a jupyter notebook looks like that:

```bash
(stable) └─❱❱❱ conda activate base                                                   +9035 17:51 ❰─┘

┌─( ~/D/src )────────────────────────────────────────────────────────────────────────( @macd2860 )─┐
(base) └─❱❱❱ jn .                                                                    +9036 17:51 ❰─┘
[I 17:51:31.745 NotebookApp] [nb_conda_kernels] enabled, 8 kernels found
[I 17:51:32.046 NotebookApp] Loading IPython parallel extension
[I 17:51:32.063 NotebookApp] [jupyter_nbextensions_configurator] enabled 0.3.0
[I 17:51:32.066 NotebookApp] Serving notebooks from local directory: /Users/klay6683/Dropbox/src
[I 17:51:32.066 NotebookApp] 0 active kernels
```

I recently reinstalled by `stable` setup, which is a Python 3.6 env with all my everyday packages and no GH master stuff.
Since the reinstall, `nb_conda_kernels` can't call conda from within the `stable` env:

```bash
(base) └─❱❱❱ conda activate stable                                                   +9037 17:52 ❰─┘

┌─( ~/D/src )────────────────────────────────────────────────────────────────────────( @macd2860 )─┐
(stable) └─❱❱❱ jn .                                                                  +9038 17:52 ❰─┘
[E 17:52:50.245 NotebookApp] [nb_conda_kernels] couldn't call conda:
    [Errno 2] No such file or directory: 'conda': 'conda'
[I 17:52:50.246 NotebookApp] [nb_conda_kernels] enabled, 0 kernels found
[I 17:52:50.540 NotebookApp] Loading IPython parallel extension
[I 17:52:50.557 NotebookApp] [jupyter_nbextensions_configurator] enabled 0.3.0
[I 17:52:50.560 NotebookApp] Serving notebooks from local directory: /Users/klay6683/Dropbox/src
[I 17:52:50.560 NotebookApp] 0 active kernels
```

while my older envs still work fine, e.g. my Python 3.5 env.

I noticed that I can of course run my work from the base env because my kernels from the other envs are being found there, but imagine it wouldn't be working there as well, then I couldn't work at all, because I don't recall anymore how to manually install kernels, so scary indeed.

I'm running these on a macOS 10.12.6 with miniconda3 and conda-forge as default.

### PR DESCRIPTION
**Pull request by benbovy**
Fixes #73 

Try first getting path to conda executable from `$CONDA_EXE`.

xref: jupyterlab/jupyterlab#4598

### CODE REVIEW

**Comment by tjd2002** [comment]
Thanks @benbovy this allows me to use nb_conda under latest anaconda (4.5.3)!

It seems this repo needs a little attention--last commits about 1 year ago, and it is still testing against conda 4.2. Are there any maintainers around? @damianavila or @bollwyvl ?

**Comment by tjd2002** [comment]
Looks like this will not be compatible with older installs of conda that do not export $CONDA_EXE. Is this a problem? See #80 for a PR that includes a backwards-compatible fix (among other changes)

**Comment by mcg1969** [comment]
To be honest, #80 is getting to unwieldy, trying to do too many things at once. It's fine with me if we try to separate concerns here. I would propose that you bring in my back-compatible logic (or equivalent) into your construction of CONDA_EXE, but that this PR be treated/reviewed/merged separately.

**Comment by benbovy** [comment]
> Looks like this will not be compatible with older installs of conda that do not export $CONDA_EXE. Is this a problem? See #80 for a PR that includes a backwards-compatible fix (among other changes)

In this PR, if `$CONDA_EXE` doen't exists then it fails back to the older behavior, i.e., trying to get `conda` from PATH, so I think it is still backward compatible.

**Comment by benbovy** [comment]
That said, #80 seems to test for a few more things, notably on windows platforms which I don't use, so it's probably better addressed there.

**Comment by mcg1969** [comment]
I agree now that the approach in #80 can at least be simplified. For #82, I've opted to pull this in directly. If #80 needs something more, it will get it ;-)

**Comment by tjd2002** [comment]
As to whether the special-casing in #80 is necessary, 

At https://github.com/Anaconda-Platform/anaconda-nb-extensions/issues/168#issuecomment-392280875, Kale Franz wrote: 
>I would wait to target any change toward conda 4.6+. [...] The big differences here are the existence of a new `conda init` command to ensure your shell is configured correctly, and then the guaranteed presence of a `CONDA_EXE` environment variable (and `CONDA_BAT` as appropriate).
(This: https://github.com/conda/conda/pull/7206 appears to be the PR that makes these changes in 4.6)

So I agree with @mcg1969 that the approach used here looks good. 

I think it is preferable to consider this separately from #82, since it is a simple fix for an issue that is happening in the wild right now (for users trying out the new-style install).

**Comment by mcg1969** [comment]
Based on discussions with @tjd2002, this is still included in #82, so this can be closed (and #73) if #82 is merged.

**Comment by benbovy** [comment]
OK, I leave this PR as is for now. Let me know when I can close this (or for maintainers, feel free to close it or merge it depending on what's best to do).

**Comment by mcg1969** [comment]
I'm still waiting on some internal decision making and @damianavila in particular for advice on how to proceed. Stay tuned. Won't be too much longer, I don't think.

**Pull request closed without merging**
