### PR TITLE
Take in full kernel specs instead of hardcoding for Python/R

### PR DESCRIPTION
**Pull request by mcg1969**
This addresses a couple of (in my view) important issues.

1. The current version only supports Python and R, so no custom kernels are supported.
2. If R exists in an environment, it _assumes_ that `irkernel` exists in the environment, but that is not always going to be the case.
3. The conda environment is not activated, which means that environments with activate scripts (e.g., for setting environment variables) will fail.

This reworks the KernelSpec object by removing the hardcoded Python/R support altogether, and replacing it with a straight reading and modification of the `kernel.json` files it finds in the environment.

It resolves #3 using a `conda-run` script that I am developing now. Effectively this script just activates the environment specified by its first argument, and calls `exec` on the remaining arguments to execute the command. It might be worth considering making this script into `nb_conda_kernels` itself instead of making it a dependency. That will complicate the packaging requirements a bit.

### CODE REVIEW

**Comment by tjd2002** [comment]
Note that #79 also deals with `conda` not being on the path in Conda 4.4+, but does not attempt to be backwards-compatible to old-style installs, as you do.

Not sure which is the preferred way forwards--do these conda_nb_kernel* extensions need to continue working with conda <=4.3?

**Comment by mcg1969** [comment]
@tjd2002 it's relatively easy to maintain compatibility with 4.3, and Anaconda does have customers that will be stuck with 4.3 for awhile. So I see no reason why not.

**Comment by mcg1969** [comment]
For me, the most important things here are 1) the ability to detect custom kernels and 2) the activation of environments. Making it work with different versions of conda is, while necessary, not my main focus.

**Comment by mcg1969** [comment]
Taking a quick run through the older PRs, I'm reasonably optimistic that with #82 and #80 we can close out every one of these other PRs.

**Pull request merged**
