### PR TITLE
Support CondaKernelSpecManager.env_filter regex

### PR DESCRIPTION
**Pull request by parente**
In some deployments, there may be conda environments present that
should not appear in the list (e.g., environments that may have
jupyter, python, R but not kernels)

### CODE REVIEW

**Comment by ericdill** [comment]
@damianavila @bollwyvl any chance of reviewing this?

**Comment by damianavila** [comment]
Sorry for the delay @ericdill and @parente... this is useful. 
I like it, let's wait (for a little bit) for @bollwyvl 's look as well, otherwise I will merge it in a few days.

**Comment by bollwyvl** [comment]
Yeah, looks good. Let's merge and move forward. I'll make some issues for some miscellany...

**Comment by parente** [comment]
Cool. Thanks!

**Pull request merged**
